# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5598eaaf96add6fb6267630bb10a24948805a16fb65e155f637bbb1d543884119cb899239aff17ecb493462ad442d294bcbe9f885666aa4e7afc5355590a81b

test:
  secret_key_base: 792e7adc9eceaa21b2a90e6be331856cddbb87fe95366edaaf0a5a49a847615441da05b115edec28a85ad5fb546a65b291fec3456a8557f93dfedd322788fda7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
